# Initial Setup 
# -------------------------------------------------
# Hugo Modules
[module]
  [module.hugoVersion]        # (optional) Mindestversion
    extended = true
    min = "0.123.0"

  [[module.imports]]
    path = "github.com/1nterfect0r/pbw_hugo_theme"
    # version = "v1.0.0"     
# -------------------------------------------------

languageCode = 'de-de'
title = 'Pfadfinder*innenstamm Passauer Wildschweine e.V'

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"


[params]
    name = "Pfadfinder*innenstamm Passauer Wildschweine e.V"
    description = "Der Pfadfinder*innenstamm Passauer Wildschweine e.V bietet Gruppenstunden für Kinder und Jugendliche an."
    favicon = "/favicon/favicon.ico"
    hasMembersArea = false # Mitgleiderbereich als Link im footer anzeigen

  [[params.contacts]]
    name = "Fiona"
    role = "Stammesführerin"
    email = "fiona.pigal@pbw.org"
    phone = "+43 664 3818112"


  [params.impressum]
    name = 'Fiona Marlene Pigal (Post an "Rechts- und Finanzträger des Pfadfinderbundes Weltenbummler e.V.")'
    address = "Spittlertorgraben 47"
    zipCity = "90429 Nürnberg"
    phone = "+43 664 3818112"
    email = "fiona.pigal@pbw.org"

    # Diese Felder sind leer, da sie für diesen Verein nicht relevant sind.
    registerCourt = "Amtsgerichts Passau"
    registerNumber = "VR 201190"

    [params.impressum.representatives]
      chairperson1 = "Fiona Marlene Pigal"
      chairperson2 = "Nico Kavermann"
      treasurer = ""

  [params.privacy]
    organizationNameNominativ = "Pfadfinder*innenstamm Passauer Wildschweine e.V"  # {{ .Site.Params.privacy.organizationNameNominativ }}
    organizationNameGenitiv = "des Pfadfinder*innenstamms Passauer Wildschweine e.V" # {{ .Site.Params.privacy.organizationNameGenitiv }}
    organizationNameDativ = "dem Pfadfinder*innenstamm Passauer Wildschweine e.V" # {{ .Site.Params.privacy.organizationNameDativ }}
    organizationNameAkkusativ = "den Pfadfinder*innenstamm Passauer Wildschweine e.V" # {{ .Site.Params.privacy.organizationNameAkkusativ }}
    contact_name = 'Fiona Marlene Pigal (Post an "Rechts- und Finanzträger des Pfadfinderbundes Weltenbummler e.V.")'
    contact_address = "Spittlertorgraben 47"
    contact_zipCity = "90429 Nürnberg"
    contact_country = "Deutschland"
    contact_phone = "+43 664 3818112"
    contact_email = "fiona.pigal@pbw.org"
    